params:
  max_depth: 20
  width: 4024
  height: 3036

calib:
  extrinsic:
    R:
      rows: 3
      cols: 3
      dt: d
      data: [-3.83495e-05 ,-0.999891,-0.0147347,  -0.00377076,0.0147348,-0.999884 , 0.999993 ,1.72161e-05,-0.00377092 ]
    T:
      rows: 3
      cols: 1
      dt: d
      data: [0.0929016, 0.0316183, 0.136342]
  intrinsic:
    cx: 1512.51235 #2005.04664860767
    cy: 1004.18006 #1607.24342386345
    fx: 3405.47215 #4628.00030763765
    fy: 3405.51992 #4643.90946043923
  distortion:
    rows: 5
    cols: 1
    dt: d
    data: [-0.116015, 0.156237, 0.000245, -0.000297, 0.000000]

cluster:
  eps: 0.40 # eps是DBSCAN算法的一个参数，它是一个浮点数，用来控制邻域的大小
  min_points: 10 # min_samples是DBSCAN算法的一个参数，它是一个整数，用来控制核心点的最小个数
  print_progress: False # 是否打印进度

filter:
  nb_neighbors: 20
  std_ratio: 2.0
  voxel_size: 0.035

field:
  Red:
    left_up: [8670,9285,420]
    left_down: [8670,9285,120]
    right_down: [8670,8885,120]
    right_up: [8670,8885,420]
  Blue:
    left_up: [0,5034,800]
    left_down: [0,5034,0]
    right_down: [3104,5113,0]
    right_up: [3104,5113,800]
  test:
    left_up: [0,0,125] # 22.5 12.5
    left_down: [0,0,0]
    right_down: [225,0,0]
    right_up: [225,0,125]
