params:
  max_depth: 20
  width: 3072
  height: 2048

calib:
  extrinsic:
    R:
      rows: 3
      cols: 3
      dt: d
      data: [0.01914, -0.99981, 0.00462, 0.00132, -0.00459, -0.99999, 0.99982, 0.01915, 0.00123]
    T:
      rows: 3
      cols: 1
      dt: d
      data: [-0.05301, 0.04890, -0.07717]
  intrinsic:
    cx: 1464.07806
    cy: 1043.84681
    fx: 3416.27346
    fy: 3416.72055
  distortion:
    rows: 1
    cols: 5
    dt: d
    data: [-0.126359, 0.198771, -0.000771, -0.000515, 0.000000]

cluster:
  eps: 0.40 # eps是DBSCAN算法的一个参数，它是一个浮点数，用来控制邻域的大小
  min_points: 10 # min_samples是DBSCAN算法的一个参数，它是一个整数，用来控制核心点的最小个数
  print_progress: False # 是否打印进度

filter:
  nb_neighbors: 20
  std_ratio: 2.0
  voxel_size: 0.035

field:
  Red:
    left_up: [0., 5233, 800]
    left_down: [0., 5233, 0]
    right_down: [4063, 4464, 0]
    right_up: [4063, 4464, 305]
  Blue:
    left_up: [0., 5233, 800]
    left_down: [0., 5233, 0]
    right_down: [4063, 4464, 0]
    right_up: [4063, 4464, 305]
  test:
    left_up: [0,0,125] # 22.5 12.5
    left_down: [0,0,0]
    right_down: [225,0,0]
    right_up: [225,0,125]
