params:
  max_depth: 20
  width: 4024
  height: 3036

calib:
  extrinsic:
    R:
      rows: 3
      cols: 3
      dt: d
      data: [0.00779  , -0.99997 , 0.00126 ,  -0.01019 , -0.00134 , -0.99995 , 0.99992 ,  0.00778  , -0.01020 ]
    T:
      rows: 3
      cols: 1
      dt: d
      data: [0.00685   , 0.04710  , -0.06953]
  intrinsic:
    cx: 1506.80292 #2005.04664860767
    cy: 1061.96113 #1607.24342386345
    fx: 3339.3597 #4628.00030763765
    fy: 3336.44881 #4643.90946043923
  distortion:
    rows: 5
    cols: 1
    dt: d
    data: [-0.083940, 0.109274, -0.000983, 0.001424, 0.000000]

cluster:
  eps: 0.40 # eps是DBSCAN算法的一个参数，它是一个浮点数，用来控制邻域的大小
  min_points: 10 # min_samples是DBSCAN算法的一个参数，它是一个整数，用来控制核心点的最小个数
  print_progress: False # 是否打印进度

filter:
  nb_neighbors: 20
  std_ratio: 1.0
  voxel_size: 0.005

field:
  Red:
    left_up: [0., 5233, 800]
    left_down: [0., 5233, 0]
    right_down: [4063, 4464, 0]
    right_up: [4063, 4464, 305]
  Blue:
    left_up: [0., 5233, 800]
    left_down: [0., 5233, 0]
    right_down: [4063, 4464, 0]
    right_up: [4063, 4464, 305]
  test:
    left_up: [0,0,125] # 22.5 12.5
    left_down: [0,0,0]
    right_down: [225,0,0]
    right_up: [225,0,125]
