path:
  stage_one_path:  "/home/rm/lsa/radar/hnurm_radar/weights/stage_one.pt" # 未测试，不行就改成绝对路径
  stage_two_path: "/home/rm/lsa/radar/hnurm_radar/weights/stage_two.pt" #
  stage_three_path: "/home/rm/lsa/radar/hnurm_radar/weights/stage_three.pt"
  tracker_path: "/home/rm/lsa/radar/hnurm_radar/configs/bytetrack.yaml"

params:
  labels: ["B1", "B2", "B3", "B4", "B5", "B7", "R1", "R2", "R3", "R4", "R5", "R7"]
  stage_one_conf: 0.1
  stage_two_conf: 0.6
  stage_three_conf: 0.5
  life_time: 90 # 生命周期

is_record: False
record_fps: 19